# Generated by Django 3.2.3 on 2021-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now=True, verbose_name='Data e hora')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('idade', models.PositiveSmallIntegerField(verbose_name='Idade')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
            ],
        ),
    ]
