# Generated by Django 3.2.3 on 2021-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=254, verbose_name='Senha')),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='datahora',
            field=models.DateTimeField(verbose_name='Data e hora'),
        ),
    ]
