# Generated by Django 3.2.3 on 2021-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210602_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.PositiveSmallIntegerField(verbose_name='Idade')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=25, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=25, verbose_name='Cidade')),
            ],
        ),
    ]
