# Generated by Django 3.2.3 on 2021-06-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupo_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='local',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fkcidadao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.cidadao'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fkgrupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.grupo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fklocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.local'),
        ),
    ]
